#include <Arduino.h>
#include <avr/pgmspace.h>
#include "MusicPlayer.h"

// taken from https://github.com/robsoncouto/arduino-songs/

extern const PROGMEM int minueteInG[] = {
  // Minuet in G - Petzold
  // Score available at https://musescore.com/user/3402766/scores/1456391

  140, // tempo
  
  NOTE_D5,  QART,     NOTE_G4,  EIGT, NOTE_A4,  EIGT, NOTE_B4,  EIGT, NOTE_C5,  EIGT, //1
  NOTE_D5,  QART,     NOTE_G4,  QART, NOTE_G4,  QART,
  NOTE_E5,  QART,     NOTE_C5,  EIGT, NOTE_D5,  EIGT, NOTE_E5,  EIGT, NOTE_FS5, EIGT,
  NOTE_G5,  QART,     NOTE_G4,  QART, NOTE_G4,  QART,
  NOTE_C5,  QART,     NOTE_D5,  EIGT, NOTE_C5,  EIGT, NOTE_B4,  EIGT, NOTE_A4,  EIGT,
  
  NOTE_B4,  QART,     NOTE_C5,  EIGT, NOTE_B4,  EIGT, NOTE_A4,  EIGT, NOTE_G4,  EIGT,//6
  NOTE_FS4, QART,     NOTE_G4,  EIGT, NOTE_A4,  EIGT, NOTE_B4,  EIGT, NOTE_G4,  EIGT,
  NOTE_A4,  HALF_DOT,
  NOTE_D5,  QART,     NOTE_G4,  EIGT, NOTE_A4,  EIGT, NOTE_B4,  EIGT, NOTE_C5,  EIGT, 
  NOTE_D5,  QART,     NOTE_G4,  QART, NOTE_G4,  QART,
  NOTE_E5,  QART,     NOTE_C5,  EIGT, NOTE_D5,  EIGT, NOTE_E5,  EIGT, NOTE_FS5, EIGT,
  
  NOTE_G5,  QART,     NOTE_G4,  QART, NOTE_G4,  QART,
  NOTE_C5,  QART,     NOTE_D5,  EIGT, NOTE_C5,  EIGT, NOTE_B4,  EIGT, NOTE_A4,  EIGT, //12
  NOTE_B4,  QART,     NOTE_C5,  EIGT, NOTE_B4,  EIGT, NOTE_A4,  EIGT, NOTE_G4,  EIGT,
  NOTE_A4,  QART,     NOTE_B4,  EIGT, NOTE_A4,  EIGT, NOTE_G4,  EIGT, NOTE_FS4, EIGT,
  NOTE_G4,  HALF_DOT,

  NOTE_D5,  QART,     NOTE_G4,  EIGT, NOTE_A4,  EIGT, NOTE_B4,  EIGT, NOTE_C5,  EIGT, //1
  NOTE_D5,  QART,     NOTE_G4,  QART, NOTE_G4,  QART,
  NOTE_E5,  QART,     NOTE_C5,  EIGT, NOTE_D5,  EIGT, NOTE_E5,  EIGT, NOTE_FS5, EIGT,
  NOTE_G5,  QART,     NOTE_G4,  QART, NOTE_G4,  QART,
  NOTE_C5,  QART,     NOTE_D5,  EIGT, NOTE_C5,  EIGT, NOTE_B4,  EIGT, NOTE_A4,  EIGT,
  
  NOTE_B4,  QART,     NOTE_C5,  EIGT, NOTE_B4,  EIGT, NOTE_A4,  EIGT, NOTE_G4,  EIGT,//6
  NOTE_FS4, QART,     NOTE_G4,  EIGT, NOTE_A4,  EIGT, NOTE_B4,  EIGT, NOTE_G4,  EIGT,
  NOTE_A4,  HALF_DOT,
  NOTE_D5,  QART,     NOTE_G4,  EIGT, NOTE_A4,  EIGT, NOTE_B4,  EIGT, NOTE_C5,  EIGT, 
  NOTE_D5,  QART,     NOTE_G4,  QART, NOTE_G4,  QART,
  NOTE_E5,  QART,     NOTE_C5,  EIGT, NOTE_D5,  EIGT, NOTE_E5,  EIGT, NOTE_FS5, EIGT,
  
  NOTE_G5,  QART,     NOTE_G4,  QART, NOTE_G4,  QART,
  NOTE_C5,  QART,     NOTE_D5,  EIGT, NOTE_C5,  EIGT, NOTE_B4,  EIGT, NOTE_A4,  EIGT, //12
  NOTE_B4,  QART,     NOTE_C5,  EIGT, NOTE_B4,  EIGT, NOTE_A4,  EIGT, NOTE_G4,  EIGT,
  NOTE_A4,  QART,     NOTE_B4,  EIGT, NOTE_A4,  EIGT, NOTE_G4,  EIGT, NOTE_FS4, EIGT,
  NOTE_G4,  HALF_DOT,

  NOTE_B5,  QART,     NOTE_G5,  EIGT, NOTE_A5,  EIGT, NOTE_B5,  EIGT, NOTE_G5,  EIGT,//17
  NOTE_A5,  QART,     NOTE_D5,  EIGT, NOTE_E5,  EIGT, NOTE_FS5, EIGT, NOTE_D5,  EIGT,
  NOTE_G5,  QART,     NOTE_E5,  EIGT, NOTE_FS5, EIGT, NOTE_G5,  EIGT, NOTE_D5,  EIGT,
  NOTE_CS5, QART,     NOTE_B4,  EIGT, NOTE_CS5, EIGT, NOTE_A4,  QART,
  NOTE_A4,  EIGT,     NOTE_B4,  EIGT, NOTE_CS5, EIGT, NOTE_D5,  EIGT, NOTE_E5,  EIGT, NOTE_FS5, EIGT,

  NOTE_G5,  QART,     NOTE_FS5, QART, NOTE_E5,  QART, //22
  NOTE_FS5, QART,     NOTE_A4,  QART, NOTE_CS5, QART,
  NOTE_D5,  HALF_DOT,
  NOTE_D5,  QART,     NOTE_G4,  EIGT, NOTE_FS5, EIGT, NOTE_G4,  QART,
  NOTE_E5,  QART,     NOTE_G4,  EIGT, NOTE_FS4, EIGT, NOTE_G4,  QART,
  NOTE_D5,  QART,     NOTE_C5,  QART, NOTE_B4,  QART,

  NOTE_A4,  EIGT,     NOTE_G4,  EIGT, NOTE_FS4, EIGT, NOTE_G4,  EIGT, NOTE_A4,  QART, //28
  NOTE_D4,  EIGT,     NOTE_E4,  EIGT, NOTE_FS4, EIGT, NOTE_G4,  EIGT, NOTE_A4,  EIGT, NOTE_B4, EIGT,
  NOTE_C5,  QART,     NOTE_B4,  QART, NOTE_A4,  QART,
  NOTE_B4,  EIGT,     NOTE_D5,  EIGT, NOTE_G4,  QART, NOTE_FS4, QART,
  NOTE_G4,  HALF_DOT,
  NOTE_END
};
