#include <Arduino.h>
#include <avr/pgmspace.h>
#include "MusicPlayer.h"

// taken from https://github.com/robsoncouto/arduino-songs/

extern const PROGMEM int pinkPanther[] = {
  
  120, // tempo
  
  NOTE_DS4, EIGT, 
  NOTE_E4,  QART_DOT, REST,     EIGT,     NOTE_FS4, EIGT,     NOTE_G4,  QART_DOT, REST,     EIGT,     NOTE_DS4, EIGT,
  NOTE_E4,  EIGT_DOT, NOTE_FS4, EIGT,     NOTE_G4,  EIGT_DOT, NOTE_C5,  EIGT,     NOTE_B4,  EIGT_DOT, NOTE_E4,  EIGT,     NOTE_G4,  EIGT_DOT, NOTE_B4, EIGT,   
  NOTE_AS4, HALF,     NOTE_A4,  SIXT_DOT, NOTE_G4,  SIXT_DOT, NOTE_E4,  SIXT_DOT, NOTE_D4,  SIXT_DOT, 
  NOTE_E4,  HALF,     REST,     QART,     REST,     EIGT,     NOTE_DS4, QART,

  NOTE_E4,  QART_DOT, REST,     EIGT,     NOTE_FS4, EIGT,     NOTE_G4,  QART_DOT, REST,     EIGT,     NOTE_DS4, EIGT,
  NOTE_E4,  EIGT_DOT, NOTE_FS4, EIGT,     NOTE_G4,  EIGT_DOT, NOTE_C5,  EIGT,     NOTE_B4,  EIGT_DOT, NOTE_G4,  EIGT,     NOTE_B4,  EIGT_DOT, NOTE_E5, EIGT,
  NOTE_DS5, FULL,   
  NOTE_D5,  HALF,     REST,     QART,     REST,     EIGT,     NOTE_DS4, EIGT, 
  NOTE_E4,  QART_DOT, REST,     EIGT,     NOTE_FS4, EIGT,     NOTE_G4,  QART_DOT, REST,     EIGT,     NOTE_DS4, EIGT,
  NOTE_E4,  EIGT_DOT, NOTE_FS4, EIGT,     NOTE_G4,  EIGT_DOT, NOTE_C5,  EIGT,     NOTE_B4,  EIGT_DOT, NOTE_E4,  EIGT,     NOTE_G4,  EIGT_DOT, NOTE_B4, EIGT,   
  
  NOTE_AS4, HALF,     NOTE_A4,  SIXT_DOT, NOTE_G4,  SIXT_DOT, NOTE_E4,  SIXT_DOT, NOTE_D4,  SIXT_DOT, 
  NOTE_E4,  QART_DOT, REST,     QART,
  REST,     QART,     NOTE_E5,  EIGT_DOT, NOTE_D5,  EIGT,     NOTE_B4,  EIGT_DOT, NOTE_A4,  EIGT,     NOTE_G4,  EIGT_DOT, NOTE_E4,  EIGT_DOT,
  NOTE_AS4, SIXT,     NOTE_A4,  EIGT_DOT, NOTE_AS4, SIXT,     NOTE_A4,  EIGT_DOT, NOTE_AS4, SIXT,     NOTE_A4,  EIGT_DOT, NOTE_AS4, SIXT,     NOTE_A4, EIGT_DOT,   
  NOTE_G4,  SIXT_DOT, NOTE_E4,  SIXT_DOT, NOTE_D4,  SIXT_DOT, NOTE_E4,  SIXT,     NOTE_E4,  SIXT,     NOTE_E4,  HALF,
  NOTE_END, NOTE_END, NOTE_END, NOTE_END, NOTE_END, NOTE_END
};
